# -----------------------------------------------------------------------------
# docker-minecraft
#
# Builds a basic docker image that can run a Minecraft server
# (http://minecraft.net/).
# -----------------------------------------------------------------------------

FROM eclipse-temurin:21-jdk

# Load in all of our config files.
ADD ./start /start
ADD ./server/server_1.21.6 /server.jar

# Fix all permissions
RUN chmod +x /start
RUN chmod +x /server.jar

# 25565 is for minecraft
EXPOSE 25565

# /start runs it.
CMD ["/start"]
